# Generated by Django 3.1.3 on 2020-11-22 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.TextField()),
                ('memo', models.TextField()),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
